---

apiVersion: batch/v1
kind: Job
metadata:
  name: aitestmate-migrator
  labels:
    {{- include "aitestmate-migrator.labels" . | nindent 4 }}
spec:
  backoffLimit: 3
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aitestmate-migrator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      containers:
        - name: aitestmate-migrator
          image: {{ .Values.image.repository }}:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          args: ["database", "migrate"]
