---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aitestmate-worker
  labels:
    # {{ include "aitestmate-worker.labels" . | nindent 4 }}
spec:
  minReadySeconds: 15
  replicas:
    {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      # {{ include "aitestmate-worker.selectorLabels" . | nindent 6 }}
  serviceName: aitestmate-worker-headless
  template:
    metadata:
      labels:
        # {{ include "aitestmate-worker.labels" . | nindent 8 }}
        # {{ with .Values.podLabels }}
        # {{ toYaml . | nindent 8 }}
        # {{ end }}
    spec:
      # {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        # {{ toYaml . | nindent 8 }}
      # {{ end }}
      serviceAccountName: aitestmate-worker-sa
      # {{ with .Values.podSecurityContext }}
      securityContext:
        # {{ toYaml . | nindent 8 }}
      # {{ end }}
      containers:
        - name: aitestmate-worker
          # {{ with .Values.securityContext }}
          securityContext:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          image: >-
            {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: >-
            {{ .Values.image.pullPolicy }}
          # {{ with (concat (default list .Values.env) (default list .Values.extraEnv) | uniq) }}
          env:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          # {{ with .Values.livenessProbe }}
          livenessProbe:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          # {{ with .Values.readinessProbe }}
          readinessProbe:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          # {{ with .Values.resources }}
          resources:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          volumeMounts:
          - name: dshm
            mountPath: /dev/shm
          - name: aitestmate-worker-home
            mountPath: /var/lib/aitestmate
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: aitestmate-worker-home
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
