apiVersion: v2
name: elasticsearch
description: A Helm chart for Elasticsearch Stack

version: 8.5.1

appVersion: "8.14.2"

dependencies:
- name: elasticsearch
  version: 8.5.1
  repository: https://helm.elastic.co
