apiVersion: v2
name: mermaid-server
description: A Helm chart for AI/Run mermaid server.

version: 1.4.0

appVersion: "1.4.0"

dependencies:
- name: mermaid-server
  version: 1.4.0
  repository: oci://%%IMAGE_REPOSITORY%%/helm-charts