---

# lookup secret once
# {{ $secret := lookup "v1" "Secret" .Release.Namespace "aitestmate-rabbitmq-secret" }}

apiVersion: v1
kind: Secret
metadata:
  name: aitestmate-rabbitmq-secret
  labels:
    # {{ include "aitestmate-rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  username: >-
    {{ dig "data" "username" ("rabbitmq" | b64enc) $secret }}
  password: >-
    {{ dig "data" "password" (randAlphaNum 24 | b64enc) $secret }}
  vhost: >-
    {{ dig "data" "vhost" ("aitm" | b64enc) $secret }}
