---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aitestmate-sysworker
  labels:
    # {{ include "aitestmate-sysworker.labels" . | nindent 4 }}
spec:
  replicas:
    {{ .Values.replicaCount }}
  selector:
    matchLabels:
      # {{ include "aitestmate-sysworker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        # {{ include "aitestmate-sysworker.labels" . | nindent 8 }}
        # {{ with .Values.podLabels }}
        # {{ toYaml . | nindent 8 }}
        # {{ end }}
    spec:
      # {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        # {{ toYaml . | nindent 8 }}
      # {{ end }}
      serviceAccountName: aitestmate-sysworker-sa
      # {{ with .Values.podSecurityContext }}
      securityContext:
        # {{ toYaml . | nindent 8 }}
      # {{ end }}
      containers:
        - name: aitestmate-sysworker
          # {{ with .Values.securityContext }}
          securityContext:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          image: >-
            {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: >-
            {{ .Values.image.pullPolicy }}
          args: ["worker", "run", "--queues", "system_tasks"]
          # {{ with (concat (default list .Values.env) (default list .Values.extraEnv) | uniq) }}
          env:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          # {{ with .Values.livenessProbe }}
          livenessProbe:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          # {{ with .Values.readinessProbe }}
          readinessProbe:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          # {{ with .Values.resources }}
          resources:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
