---

apiVersion: v1
kind: Service
metadata:
  name: aitestmate-rabbitmq-headless
  labels:
    {{- include "aitestmate-rabbitmq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  selector:
    {{- include "aitestmate-rabbitmq.selectorLabels" . | nindent 4 }}
