apiVersion: v2
name: codemie-ui
description: A Helm chart for AI/Run UI

version: %%IMAGE_VERSION%%

appVersion: "%%IMAGE_VERSION%%"

dependencies:
- name: codemie-ui
  version: %%IMAGE_VERSION%%
  repository: oci://%%IMAGE_REPOSITORY%%/helm-charts