---

apiVersion: v1
kind: Service
metadata:
  name: aitestmate-elasticsearch-headless
  labels:
    {{- include "aitestmate-elasticsearch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
  selector:
    {{- include "aitestmate-elasticsearch.selectorLabels" . | nindent 4 }}
