---

# lookup secret once
# {{ $secret := lookup "v1" "Secret" .Release.Namespace "aitestmate-kibana-secret" }}

apiVersion: v1
kind: Secret
metadata:
  name: aitestmate-kibana-secret
  labels:
    # {{ include "aitestmate-kibana.labels" . | nindent 4 }}
type: Opaque
data:
  username: >-
    {{ dig "data" "username" ("kibana_system" | b64enc) $secret }}
  password: >-
    {{ dig "data" "password" (randAlphaNum 24 | b64enc) $secret }}
