apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.neo4j.auth.secretName | default "aice-neo4j-secret" | quote }}
  labels:
    app: {{ .Release.Name }}-secret
type: Opaque
data:
  username: {{ .Values.neo4j.auth.username | b64enc | quote }}
  password: {{ .Values.neo4j.auth.password | b64enc | quote }}
  auth: {{ printf "%s/%s" .Values.neo4j.auth.username .Values.neo4j.auth.password | b64enc | quote }}