---

# lookup secret once
# {{ $secret := lookup "v1" "Secret" .Release.Namespace "aitestmate-postgres-secret" }}

apiVersion: v1
kind: Secret
metadata:
  name: aitestmate-postgres-secret
  labels:
    # {{ include "aitestmate-postgres.labels" . | nindent 4 }}
type: Opaque
data:
  username: >-
    {{ dig "data" "username" ("aitestmate" | b64enc) $secret }}
  password: >-
    {{ dig "data" "password" (randAlphaNum 24 | b64enc) $secret }}
  database: >-
    {{ dig "data" "database" ("aitestmate" | b64enc) $secret }}
