apiVersion: v2
name: neo4j
description: A Helm chart for Neo4j database with APOC plugins
type: application
version: 0.1.0
# appVersion: "5.26.3"
appVersion: "5.26.9"
icon: https://neo4j.com/favicon.ico
