apiVersion: v2
name: codemie
description: A Helm chart for AI/Run API

version: 1.4.0

appVersion: "1.4.0"

dependencies:
- name: codemie
  version: 1.4.0
  repository: oci://%%IMAGE_REPOSITORY%%/helm-charts
