apiVersion: v1.edp.epam.com/v1
kind: KeycloakClientScope
metadata:
  name: codemie
  annotations:
    edp.epam.com/preserve-resources-on-deletion: "true"
spec:
  description: default scope required for oauth2-proxy
  name: codemie
  protocol: openid-connect
  protocolMappers:
    - config:
        access.token.claim: 'true'
        included.client.audience: codemie
      name: oauth2-proxy-audience
      protocol: openid-connect
      protocolMapper: oidc-audience-mapper
  realmRef:
    kind: KeycloakRealm
    name: codemie-prod
