---

# lookup secret once
# {{ $secret := lookup "v1" "Secret" .Release.Namespace "aitestmate-redis-secret" }}

apiVersion: v1
kind: Secret
metadata:
  name: aitestmate-redis-secret
  labels:
    # {{ include "aitestmate-redis.labels" . | nindent 4 }}
type: Opaque
data:
  password: >-
    {{ dig "data" "password" (randAlphaNum 24 | b64enc) $secret }}
