---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aitestmate-redis
  labels:
    # {{ include "aitestmate-redis.labels" . | nindent 4 }}
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      # {{ include "aitestmate-redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        # {{ include "aitestmate-redis.labels" . | nindent 8 }}
    spec:
      # {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        # {{ toYaml . | nindent 8 }}
      # {{ end }}
      # {{ with .Values.podSecurityContext }}
      securityContext:
        # {{ toYaml . | nindent 8 }}
      # {{ end }}
      containers:
        - name: aitestmate-redis
          image: >-
            {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: >-
            {{ .Values.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.port }}
          # {{ with (concat (default list .Values.env) (default list .Values.extraEnv) | uniq) }}
          env:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          # {{ with .Values.resources }}
          resources:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          volumeMounts:
          - name: aitestmate-redis-data
            mountPath: /var/lib/redis
  volumeClaimTemplates:
    - metadata:
        name: aitestmate-redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
