---

# lookup secret once
# {{ $secret := lookup "v1" "Secret" .Release.Namespace "aitestmate-elasticsearch-secret" }}

apiVersion: v1
kind: Secret
metadata:
  name: aitestmate-elasticsearch-secret
  labels:
    # {{ include "aitestmate-elasticsearch.labels" . | nindent 4 }}
type: Opaque
data:
  username: >-
    {{ dig "data" "username" ("elastic" | b64enc) $secret }}
  password: >-
    {{ dig "data" "password" (randAlphaNum 24 | b64enc) $secret }}
